### ISSUE TITLE
Reading from stdin panics

### ISSUE THREAD

**Issue by cherryblossom000** [eliaperantoni/Koi#11]
Using the example from [the docs](https://koi-lang.dev/#cmdline):

```
$ echo 'print("Koi")' | koi -s 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:77:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe this is due to this line:

https://github.com/eliaperantoni/Koi/blob/caa13f7bdb1754627dba0d90c733da8ad73107a1/src/main.rs#L77

Providing the `-s` option conflicts with providing a path, so naturally `matches.value_of("path") == None`.

Maybe the root can be set to the [current directory](https://doc.rust-lang.org/std/env/fn.current_dir.html) if reading from stdin?

**Comment by eliaperantoni** [comment]
Hi @cherryblossom000, you are totally right! (Sorry for the abysmal delay).
I have fixed this and other issues with the import system, a new release is available if you want to try it out!

```
~/code/koi > echo 'print("Koi")' | koi -s 
Koi
```

Closing this for now but feel free to reopen if more issues arise.
