### ISSUE TITLE
Asterisk expansion

### ISSUE THREAD

**Issue by manfredlotz** [eliaperantoni/Koi#13]
Just a question. How would I issue a command like this?

```
ls -l *.pdf
```

**Comment by eliaperantoni** [comment]
Hello, Koi doesn't really support globbing. You can perform the command you mentioned as such:

```
ls -l { $(ls).split("\n").filter(fn(s) {return s.matches(".*\.pdf")}) }
```

which I'll admit, is really really bad.

Would something like:

```
ls -l {glob("*.pdf")}
```

be too verbose?

**Comment by manfredlotz** [comment]
A question is if asterisk could be used like in a shell script. I have no idea if it would be worth to try. Perhaps there are complications I don't have any idea of.

So, for the time being putting the `$(ls).split...` line into a `glob` function would be sufficient I think. 

Thank you.

**Comment by manfredlotz** [comment]
I guess it might be a good idea to offer the globbing mechanism from the `glob` crate.

**Comment by eliaperantoni** [comment]
Hi @manfredlotz, I've been a little busy these days but I'll be sure to resolve the issue by the weekend! For any globbing needs I will surely rely on the `glob` crate. I'm also still wondering how to go about it though I'm leaning towards a native `glob` function.

**Comment by manfredlotz** [comment]
I think your suggestion `ls -l {glob("*.pdf")}` is good. Perhaps make `glob` an internal function which then uses the `glob` crate.

**Comment by eliaperantoni** [comment]
Yeah I wouldn't want to make the language too complicated.

The user shouldn't be required to know that this:
```
echo {some_var}
```
might cause globbing depending on the value of `some_var` or that `echo *` is not the same as `echo '*'` (I'm looking at you, Bash).

I implemented the `glob` native function, check it out in release `v1.8.0`!

**Comment by manfredlotz** [comment]
I tried it as given above, i.e. `ls -l {glob("*.pdf")}` 

Works fine. I think this is a good solution, also from a security point of view.

Just see that this
```
let pat = "s*.pdf"
ls -l {glob({pat})}
```
doesn't work. Is this a mistake on my side?

BTW: version needs update in `main.rs`

**Comment by manfredlotz** [comment]
But this works

```
let pat = "s*.pdf"
let result = glob(pat)
ls -l {result}
```

**Comment by eliaperantoni** [comment]
That's because `result` is an array. What I would find confusing is a string implicitly expanding into multiple elements, but with an array it is expected.

```
let files = ['passwd', 'group']
echo {files}
```
prints:
```
passwd group
```
