### ISSUE TITLE
Possible multi-pass compilation/ parsing

### ISSUE THREAD

**Issue by Fuwn** [eliaperantoni/Koi#3]
# Issue
As it stands, if a function is called before it is declared positionally, it is not recognized, a possible multi-pass compilation/ parsing system could properly identify these symbols and fix what Bash failed to include.

## Example
```koi
print(something()) # This would cause a panic because it is declared after being called.

fn something() {
  return "nothing"
}
```

## Notes
Even the ability to predeclare functions could prove useful, however, order-independent function invoking is much more of a priority than something like this;
```koi
fn something() # Mostly just syntactic sugar.

print(something())

fn something() {
  return "nothing"
}
```

**Comment by eliaperantoni** [comment]
I really don't like the pre-declaration of functions which reminds me of C.
Doing a 2-pass interpretation where we first declare all the functions in the global scope is actually do-able and not too difficult.

**Comment by eliaperantoni** [comment]
Upon further thinking-about-it (sorry for the abysmal delay) I decided that this shouldn't need any changes. Multi-pass compilation (but not really, it's an interpreted language) would slow down the interpreter quite a bit.

As a scripting language, I think the user should be expected to write the program in such a way that it can be executed from top to bottom with no undefined identifier errors.

Take Python for instance, this won't work:

```python
print(double(5))

def double(n):
    return 2*x
```

as it doesn't in Koi:

```
print(double(5))

fn double(n) {
    return 2*n
}
```

but this is fine:

```
fn print_double(n) {
    return print(double(n))
}

fn double(n) {
    return 2*n
}

print_double(5)
```
